# Generated by Django 5.2.9 on 2026-01-05 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedbackLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id_val", models.IntegerField(blank=True, null=True)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "feedback_logs",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roll_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("course", models.CharField(blank=True, max_length=50, null=True)),
                ("semester", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_score", models.FloatField()),
                (
                    "predicted_grade",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("average_marks", models.FloatField(blank=True, null=True)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="analytics.student",
                    ),
                ),
            ],
            options={
                "db_table": "predictions",
            },
        ),
        migrations.CreateModel(
            name="SemesterPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.IntegerField()),
                ("sgpa", models.FloatField(blank=True, null=True)),
                ("cgpa", models.FloatField(blank=True, null=True)),
                ("attendance_percentage", models.FloatField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_performances",
                        to="analytics.student",
                    ),
                ),
            ],
            options={
                "db_table": "semester_performance",
                "unique_together": {("student", "semester")},
            },
        ),
        migrations.CreateModel(
            name="AcademicRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=100)),
                ("marks_obtained", models.FloatField()),
                ("total_marks", models.FloatField()),
                ("grade", models.CharField(blank=True, max_length=5, null=True)),
                ("grade_point", models.IntegerField(blank=True, null=True)),
                ("attendance_percentage", models.FloatField(blank=True, null=True)),
                ("semester", models.IntegerField()),
                ("subject_credits", models.IntegerField(default=4)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_records",
                        to="analytics.student",
                    ),
                ),
            ],
            options={
                "db_table": "academic_records",
                "unique_together": {("student", "subject_name", "semester")},
            },
        ),
    ]
